version: "3.8"

services:
  # Banco de Dados PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: platform-postgres-dev
    environment:
      - POSTGRES_DB=${DB_NAME:-microservices_platform}
      - POSTGRES_USER=${DB_USERNAME:-platform_user}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-platform_password}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./shared/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - platform-network-dev
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${DB_USERNAME:-platform_user} -d ${DB_NAME:-microservices_platform}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis
  redis:
    image: redis:7-alpine
    container_name: platform-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis_data_dev:/data
    networks:
      - platform-network-dev
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: platform-rabbitmq-dev
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME:-guest}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD:-guest}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_VHOST:-/}
    ports:
      - "5672:5672" # AMQP port
      - "15672:15672" # Management UI port
    volumes:
      - rabbitmq_data_dev:/var/lib/rabbitmq
    networks:
      - platform-network-dev
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Microserviço de Transferência (Dev)
  transfer-service-dev:
    build:
      context: ./microservices/transfer-service
      dockerfile: Dockerfile
      target: development
    container_name: transfer-service-dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - API_PREFIX=api/v1
      # Configurações do banco de dados
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=${DB_USERNAME:-platform_user}
      - DB_PASSWORD=${DB_PASSWORD:-platform_password}
      - DB_NAME=${DB_NAME:-microservices_platform}
      # Configurações do RabbitMQ
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME:-guest}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD:-guest}
      - RABBITMQ_VHOST=${RABBITMQ_VHOST:-/}
      # Configurações do Redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./microservices/transfer-service:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - platform-network-dev
    restart: unless-stopped
    command: npm run start:dev

  # Microserviço de Cliente (Dev)
  client-service-dev:
    build:
      context: ./microservices/client-service
      dockerfile: Dockerfile
      target: development
    container_name: client-service-dev
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - API_PREFIX=api/v1
      # Configurações do banco de dados
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=${DB_USERNAME:-platform_user}
      - DB_PASSWORD=${DB_PASSWORD:-platform_password}
      - DB_NAME=${DB_NAME:-microservices_platform}
      # Configurações do RabbitMQ
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME:-guest}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD:-guest}
      - RABBITMQ_VHOST=${RABBITMQ_VHOST:-/}
      # Configurações do Redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      # Configurações JWT
      - JWT_SECRET=${JWT_SECRET:-your-super-secret-key-change-in-production}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-15m}
      - JWT_REFRESH_EXPIRES_IN=${JWT_REFRESH_EXPIRES_IN:-7d}
    volumes:
      - ./microservices/client-service:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - platform-network-dev
    restart: unless-stopped
    command: npm run start:dev

volumes:
  postgres_data_dev:
    driver: local
  redis_data_dev:
    driver: local
  rabbitmq_data_dev:
    driver: local

networks:
  platform-network-dev:
    driver: bridge
